branch-defaults:
  default:
    environment: Danghoangthienp4-env
    group_suffix: null
global:
  application_name: danghoangthien-p4
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
